### ISSUE TITLE
讨教一下移动APP端怎么接入shiro-cas业务服务？

### ISSUE THREAD

**Issue by hsj-xiaokang** [willwu1984/springboot-cas-shiro#1]
你好，我也弄这个好几天了，现在传统单体，前后端的都弄好了。
讨教一下移动APP端怎么接入shiro-cas业务服务？尝试好多网上的博客利用rest方式，APP原生客户端代码访问cas认证中心获取TGT，然后再获取ST，然后携带ST访问shiro-cas业务服务，发现不管用，还是被重定向到cas认证中心了。。--能否讨教一下这个问题，你遇到APP端怎么解决这个问题？谢谢。

**Comment by hsj-xiaokang** [comment]
能否留个QQ

**Comment by willwu1984** [comment]
抱歉，没有使用过移动端接入。不过可以考虑直接使用cas的rest api接口。
